"""insurance applications

Revision ID: 5399309cf596
Revises: 5e3d93b6d9af
Create Date: 2026-09-29 15:37:38.701091
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '5399309cf596'
down_revision: Union[str, None] = '5e3d93b6d9af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=True),
    sa.Column('crop', sa.String(length=80), nullable=False),
    sa.Column('coverage_type', sa.String(length=32), nullable=False),
    sa.Column('insured_value_inr', sa.Float(), nullable=False),
    sa.Column('requested_coverage_inr', sa.Float(), nullable=False),
    sa.Column('origin', sa.String(length=240), nullable=False),
    sa.Column('destination', sa.String(length=240), nullable=False),
    sa.Column('harvest_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_applications_farmer_id'), 'insurance_applications', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_insurance_applications_shipment_id'), 'insurance_applications', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_insurance_applications_status'), 'insurance_applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurance_applications_status'), table_name='insurance_applications')
    op.drop_index(op.f('ix_insurance_applications_shipment_id'), table_name='insurance_applications')
    op.drop_index(op.f('ix_insurance_applications_farmer_id'), table_name='insurance_applications')
    op.drop_table('insurance_applications')
    # ### end Alembic commands ###