"""business marketplace workflows

Revision ID: 5e3d93b6d9af
Revises: 0001_initial
Create Date: 2026-09-29 15:33:31.061280
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '5e3d93b6d9af'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('crop', sa.String(length=80), nullable=False),
    sa.Column('variety', sa.String(length=120), nullable=False),
    sa.Column('grade', sa.String(length=80), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('available_quantity_kg', sa.Float(), nullable=False),
    sa.Column('minimum_order_kg', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('pickup_location', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_listings_crop'), 'business_listings', ['crop'], unique=False)
    op.create_index(op.f('ix_business_listings_seller_id'), 'business_listings', ['seller_id'], unique=False)
    op.create_index(op.f('ix_business_listings_status'), 'business_listings', ['status'], unique=False)
    op.create_index('ix_business_listings_status_crop', 'business_listings', ['status', 'crop'], unique=False)
    op.create_table('business_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('legal_name', sa.String(length=180), nullable=False),
    sa.Column('business_type', sa.String(length=48), nullable=False),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gst_number')
    )
    op.create_index(op.f('ix_business_profiles_is_verified'), 'business_profiles', ['is_verified'], unique=False)
    op.create_index(op.f('ix_business_profiles_user_id'), 'business_profiles', ['user_id'], unique=True)
    op.create_table('business_transport_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('pickup', sa.String(length=240), nullable=False),
    sa.Column('destination', sa.String(length=240), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('truck_count', sa.Integer(), nullable=False),
    sa.Column('delivery_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_transport_requests_requester_id'), 'business_transport_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_business_transport_requests_status'), 'business_transport_requests', ['status'], unique=False)
    op.create_table('business_locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_locations_business_id'), 'business_locations', ['business_id'], unique=False)
    op.create_table('business_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('current_offer_per_kg', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['business_listings.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_orders_buyer_id'), 'business_orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_business_orders_listing_id'), 'business_orders', ['listing_id'], unique=False)
    op.create_index(op.f('ix_business_orders_seller_id'), 'business_orders', ['seller_id'], unique=False)
    op.create_index(op.f('ix_business_orders_status'), 'business_orders', ['status'], unique=False)
    op.create_table('business_transport_quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('carrier_id', sa.String(length=36), nullable=False),
    sa.Column('price_inr', sa.Float(), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['business_transport_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_transport_quotes_carrier_id'), 'business_transport_quotes', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_business_transport_quotes_request_id'), 'business_transport_quotes', ['request_id'], unique=False)
    op.create_index(op.f('ix_business_transport_quotes_status'), 'business_transport_quotes', ['status'], unique=False)
    op.create_table('business_negotiation_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['business_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_negotiation_events_actor_id'), 'business_negotiation_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_business_negotiation_events_order_id'), 'business_negotiation_events', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_negotiation_events_order_id'), table_name='business_negotiation_events')
    op.drop_index(op.f('ix_business_negotiation_events_actor_id'), table_name='business_negotiation_events')
    op.drop_table('business_negotiation_events')
    op.drop_index(op.f('ix_business_transport_quotes_status'), table_name='business_transport_quotes')
    op.drop_index(op.f('ix_business_transport_quotes_request_id'), table_name='business_transport_quotes')
    op.drop_index(op.f('ix_business_transport_quotes_carrier_id'), table_name='business_transport_quotes')
    op.drop_table('business_transport_quotes')
    op.drop_index(op.f('ix_business_orders_status'), table_name='business_orders')
    op.drop_index(op.f('ix_business_orders_seller_id'), table_name='business_orders')
    op.drop_index(op.f('ix_business_orders_listing_id'), table_name='business_orders')
    op.drop_index(op.f('ix_business_orders_buyer_id'), table_name='business_orders')
    op.drop_table('business_orders')
    op.drop_index(op.f('ix_business_locations_business_id'), table_name='business_locations')
    op.drop_table('business_locations')
    op.drop_index(op.f('ix_business_transport_requests_status'), table_name='business_transport_requests')
    op.drop_index(op.f('ix_business_transport_requests_requester_id'), table_name='business_transport_requests')
    op.drop_table('business_transport_requests')
    op.drop_index(op.f('ix_business_profiles_user_id'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_is_verified'), table_name='business_profiles')
    op.drop_table('business_profiles')
    op.drop_index('ix_business_listings_status_crop', table_name='business_listings')
    op.drop_index(op.f('ix_business_listings_status'), table_name='business_listings')
    op.drop_index(op.f('ix_business_listings_seller_id'), table_name='business_listings')
    op.drop_index(op.f('ix_business_listings_crop'), table_name='business_listings')
    op.drop_table('business_listings')
    # ### end Alembic commands ###